### ISSUE TITLE
BTP ABAP Trial - Issue when linking any github.com repository

### ISSUE THREAD

**Issue by attilaberencsi** [abapGit/abapGit#5677]
Hello ABAPGit Team,

when I am trying to connect from EU BTP ABAP Environment Trial(Shared instance) to any public github.com repository the operation: Linking repository is hanging forever after successfully selecting the proper branch and the Transport Request.

![image](https://user-images.githubusercontent.com/20442467/177510523-56db0b93-93df-4e2e-93ca-6d26e6fbb8b4.png)

I checked the eclipse error log, and found the following: 

Unhandled event loop exception

java.lang.NullPointerException: Cannot invoke "org.abapgit.adt.backend.model.abapgitrepositories.IRepository.getLinks()" because "repository" is null
	at org.abapgit.adt.ui.internal.util.AbapGitService.isSelectivePullSupported(AbapGitService.java:76)
	at org.abapgit.adt.ui.internal.repositories.AbapGitView.openSelectivePullWizard(AbapGitView.java:600)
	at org.abapgit.adt.ui.internal.repositories.AbapGitView.access$9(AbapGitView.java:588)
	at org.abapgit.adt.ui.internal.repositories.AbapGitView$16.run(AbapGitView.java:516)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:453)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

Session data

eclipse.buildId=4.24.0.I20220607-0700
java.version=17.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=hu_HU
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -data file:/C:/Users/attil/Work/Software/Working/ADT3/attila/ -product org.eclipse.epp.package.java.product

I tried to reinstall eclipse and ABAP Developer Tools + plus the ABAPGit plugin, and also use SAP Machine JDK instead of the built-in JAVA release, but no luck, still facing the issue.

 I was able to pull existing repositories from github.com, the issue happens when adding new one only.

Can You please advise, is that because of some issue with the BTP ABAP Environment
![image](https://user-images.githubusercontent.com/20442467/177512485-87f14ec5-5f2d-4163-8a9c-618c2914331f.png)

or my workstation or somehow related to the plugin ?

Thank You in advance
Kind regards, Attila

**Comment by mbtools** [comment]
Since it fails in Eclipse, please open an issue at https://github.com/abapGit/ADT_Frontend.
